### ISSUE TITLE
Include   travis-ci template

### ISSUE THREAD

**Issue by rjpbonnal** [rjpbonnal/bioruby-gem#17]
Service: http://about.travis-ci.org/

Example:
https://github.com/pjotrp/bioruby-gem/blob/master/doc/integration-testing.md

**Comment by pjotrp** [comment]
Done.

**Comment by rjpbonnal** [comment]
merged and released

**Comment by pjotrp** [comment]
should be closed

**Comment by pjotrp** [comment]
can you close this issue?
