### ISSUE TITLE
biogem should always create ./test/data dirs

### ISSUE THREAD

**Issue by pjotrp** [rjpbonnal/bioruby-gem#28]
The following data dirs should be created

./test/data/input
./test/data/regression
./test/data/rspec
./test/data/cucumber

**Comment by wwood** [comment]
This won't create spec/data though, for rspec users.

**Comment by rjpbonnal** [comment]
You mean that we also need spec/data dir ?
Is is better to have a common path for different testing systems and their data or what ? https://www.relishapp.com/rspec/rspec-core/v/2-12/docs/configuration/default-path
I should check if it possible to configure custom path for other tools

**Comment by wwood** [comment]
Thanks. I do not know what the best opinion is here, but not knowing my first guess was to use spec/data.

Maybe what would be more useful is to make the base directory available to the person writing the test, so the user doesn't have to worry? I tend to define TEST_DATA_DIR in spec_helper.rb for instance.

**Comment by pjotrp** [comment]
Let's not overdo it guys. I think biogem should remain minimalistic.
