### ISSUE TITLE
mkdir problem

### ISSUE THREAD

**Issue by pjotrp** [rjpbonnal/bioruby-gem#3]
./bioruby-gem/bin/biogem --with-bin --with-test-data --rspec name

gives 

```
    create  README.rdoc
    create  .document
    create  lib
    create  lib/bio-name.rb
    create  spec
    create  spec/spec_helper.rb
    create  spec/bio-name_spec.rb
    create  .rspec
```

/usr/local/lib/ruby/1.9.1/fileutils.rb:243:in `mkdir': No such file or directory - bioruby-name/test/data (Errno::ENOENT)
        from /usr/local/lib/ruby/1.9.1/fileutils.rb:243:in`fu_mkdir'
        from /usr/local/lib/ruby/1.9.1/fileutils.rb:172:in `block in mkdir'
        from /usr/local/lib/ruby/1.9.1/fileutils.rb:171:in`each'
        from /usr/local/lib/ruby/1.9.1/fileutils.rb:171:in `mkdir'
        from /home/wrk/.gems/gems/jeweler-1.5.2/lib/jeweler/generator.rb:236:in`mkdir_in_target'
        from /mnt/auto/bflash/git/opensource/ruby/bioruby-gem/lib/bio-gem/mod/jeweler.rb:75:in `create_files'
        from /home/wrk/.gems/gems/jeweler-1.5.2/lib/jeweler/generator.rb:118:in`run'
        from /mnt/auto/bflash/git/opensource/ruby/bioruby-gem/lib/bio-gem/application.rb:34:in `run!'
        from ./bioruby-gem/bin/biogem:13:in`<main>'

I think it misses ./test for ./test/data

**Comment by rjpbonnal** [comment]
Selecting --spec Jeweler does not create the test directory. I modified the mod code to check if there is a test directory, when the user select --with-test-data and if not it creates the test directory before creating the data directory.
