### ISSUE TITLE
Error during biogem creation with GitHub token

### ISSUE THREAD

**Issue by fstrozzi** [rjpbonnal/bioruby-gem#38]
The biogem tool raises an error when a new biogem is created, because it is checking for the GitHub token that does not exist anymore https://github.com/blog/1090-github-api-moving-on

This is the error message:
No github.token found in ~/.gitconfig. Please tell git about your GitHub account (see http://github.com/blog/180-local-github-config for details). For example: git config --global github.token 6ef8395fecf207165f1a82178ae1b984

**Comment by homonecloco** [comment]
You can add a random token, since github is not using tokens any more. but still looks patchy

**Comment by rjpbonnal** [comment]
it should be fixed using new github api.
