### ISSUE TITLE
biogem always creates github repo

### ISSUE THREAD

**Issue by pjotrp** [rjpbonnal/bioruby-gem#9]
Even when not using the switch.

**Comment by rjpbonnal** [comment]
Yes is the default behavior, using the switch is annoying and not intuitive for beginners, I suppose they expect to have the repo there, not to create it by hand using github interface.

**Comment by pjotrp** [comment]
So we should rename the switch to -no-create-github, right?

**Comment by rjpbonnal** [comment]
ideally yes :-), I'll do that

**Comment by rjpbonnal** [comment]
Fixed.
